### ISSUE TITLE
Depend on ol-man instead of org-man

### ISSUE THREAD

**Issue by tarsius** [seanohalpin/org-link-minor-mode#7]
`org-man.el` has been renamed to `ol-man.el`, see https://code.orgmode.org/bzg/org-mode/commit/499c0a50cc4b11e37b91374af23cb27ab8fc20d2, so you should depend on `ol-man`. Because the change to Org has not made it into a release yet, you might want to soft depend on both features for the time being.

**Comment by 717g301github** [comment]
If I change org-man in source to ol-man I still get problem.

Problems while trying to load feature ‘ol-man’

I am using latest versions of Org and Emacs

**Comment by 717g301github** [comment]
I found ox-man -- not ol-man

But anyway, this packge does ot work

**Comment by tarsius** [comment]
Org 9.3 has been released. You should require the renamed library now.
